<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="KylesPC" name="com.revature.util.ExceptionAspectTest" tests="4" failures="0" timestamp="16 Oct 2019 19:36:38 GMT" time="0.043" errors="0">
  <testcase name="LogExceptionTestExceptionMessage" time="0.006" classname="com.revature.util.ExceptionAspectTest"/>
  <testcase name="LogExceptionTestLogMessage" time="0.034" classname="com.revature.util.ExceptionAspectTest"/>
  <testcase name="LogExceptionTestLogLevel" time="0.002" classname="com.revature.util.ExceptionAspectTest"/>
  <testcase name="LogException_Overload_Test" time="0.001" classname="com.revature.util.ExceptionAspectTest"/>
</testsuite> <!-- com.revature.util.ExceptionAspectTest -->
